language: elixir
elixir:
  - 1.6
otp_release:
  - 19.3
  - 20.1
addons:
  postgresql: "9.4"
before_script:
  - MIX_ENV=test mix deps.get
  - nvm install 8.10 && nvm use 8.10
  - npm install -g apollo
after_script:
  - MIX_ENV=test mix inch.report
  - apollo schema:publish --endpoint="http://devapiraw.coderplanets.com/graphiql"
script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - mix test &&  MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - $HOME/.cargo
    - deps
    - _build
