language: elixir
elixir:
  - 1.6
otp_release:
  - 19.3
  - 20.1
addons:
  postgresql: "9.4"
before_script:
  - MIX_ENV=test mix deps.get
after_script:
  - MIX_ENV=test mix inch.report
script:
  - mix test &&  MIX_ENV=test mix coveralls.travis
